name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.group == 'Downstream' }}
    strategy:
      fail-fast: false
      matrix:
        group:
          - Core
          - OptimizationBBO
          - OptimizationCMAEvolutionStrategy
          - OptimizationEvolutionary
          - OptimizationFlux
          - OptimizationGCMAES
          - OptimizationMetaheuristics
          - OptimizationMOI
          - OptimizationMultistartOptimization
          - OptimizationNLopt
          #- OptimizationNonconvex
          - OptimizationNOMAD
          - OptimizationOptimJL
          - OptimizationOptimisers
          - OptimizationQuadDIRECT
          - OptimizationSpeedMapping
          - OptimizationPolyalgorithms
        version:
          - '1'
          - '1.6'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - if: ${{ matrix.group == 'OptimizationQuadDIRECT' }}
        run: julia --project -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url  = "https://github.com/HolyLab/HolyLabRegistry.git")); Pkg.add("QuadDIRECT")'
      - uses: julia-actions/julia-runtest@v1
        env:
          GROUP: ${{ matrix.group }}
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: >
                  src,
                  lib/OptimizationBBO,
                  lib/OptimizationCMAEvolutionStrategy,
                  lib/OptimizationEvolutionary,
                  lib/OptimizationFlux,
                  lib/OptimizationGCMAES,
                  lib/OptimizationMOI,
                  lib/OptimizationMetaheuristics,
                  lib/OptimizationMultistartOptimization,
                  lib/OptimizationNLopt,
                  lib/OptimizationNOMAD,
                  lib/OptimizationNonconvex,
                  lib/OptimizationOptimJL,
                  lib/OptimizationOptimisers,
                  lib/OptimizationPolyalgorithms,
                  lib/OptimizationQuadDIRECT,
                  lib/OptimizationSpeedMapping
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
