name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ --code-coverage=user docs/make.jl
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: >
                  src,
                  lib/OptimizationBBO,
                  lib/OptimizationCMAEvolutionStrategy,
                  lib/OptimizationEvolutionary,
                  lib/OptimizationFlux,
                  lib/OptimizationGCMAES,
                  lib/OptimizationMOI,
                  lib/OptimizationMetaheuristics,
                  lib/OptimizationMultistartOptimization,
                  lib/OptimizationNLopt,
                  lib/OptimizationNOMAD,
                  lib/OptimizationNonconvex,
                  lib/OptimizationOptimJL,
                  lib/OptimizationOptimisers,
                  lib/OptimizationPolyalgorithms,
                  lib/OptimizationQuadDIRECT,
                  lib/OptimizationSpeedMapping
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
