name: Downgrade
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['1']
        group:
          - Core
          - OptimizationBBO
          - OptimizationCMAEvolutionStrategy
          - OptimizationEvolutionary
          - OptimizationFlux
          - OptimizationGCMAES
          - OptimizationMetaheuristics
          - OptimizationMOI
          - OptimizationMultistartOptimization
          - OptimizationNLopt
          #- OptimizationNonconvex
          - OptimizationNOMAD
          - OptimizationOptimJL
          - OptimizationOptimisers
          - OptimizationPRIMA
          - OptimizationQuadDIRECT
          - OptimizationSpeedMapping
          - OptimizationPolyalgorithms
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: cjdoris/julia-downgrade-compat-action@v1
#        if: ${{ matrix.version == '1.6' }}
        with:
          skip: Pkg,TOML
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          GROUP: ${{ matrix.group }}